version: '3.8'
services:
  api:
    container_name: api
    build: 
      context: ./api
      dockerfile: ./Dockerfile.prod
    networks:
      - ft_network
    volumes:
      - cdn:/api/uploads/
    env_file: .env
  application:
    container_name: application
    build:
      context: ./app
      dockerfile: ./Dockerfile.prod
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_INTRA_LOGIN_URL=${VITE_INTRA_LOGIN_URL}
    networks:
      - ft_network
  db:
    image: postgres:15.3
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" 
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/
    networks:
      - ft_network
  server:
    container_name: server
    image: nginx:1.25.1-alpine
    networks:
      - ft_network
    depends_on:
      - application
      - api
    volumes:
      - ./nginx/config/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/ssl/
      - cdn:/var/www/cdn/
    ports:
      - "80:80"
      - "443:443"
networks:
  ft_network:
    driver: bridge
volumes:
  cdn:
    driver_opts:
      type: none
      o: bind
      device: ${CDN_PATH}

